# Generated by Django 4.0.4 on 2022-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Email_name', models.CharField(max_length=100)),
                ('Conatct_Number', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
